version: '3.6'
services:
  discordbot:
    restart: unless-stopped
    build:
      context: src
      dockerfile: Dockerfile
    image: hazardous-killbot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      USE_REDIS: false
    volumes:
      - ./config:/workspace/dist/config:delegated

networks:
  default:
    name: bot-network
    driver: bridge
